### ISSUE TITLE
Can not read property 'string' of undefined

### ISSUE THREAD

**Issue by veiculu** [Osedea/react-native-action-bar#10]
Can not read property 'string' of undefined.. seems like prop-type is creating issues.

**Comment by adrienthiery** [comment]
Hi @veiculu ,

Yup, I need to update the lib 😅 

Been super busy these past few months. I'll try to take care of it today :)

**Comment by adrienthiery** [comment]
Hi @veiculu,

It should be all good in `react-native-action-bar@2.0.3`.

Don't hesitate to ask if you have other issues 😄
