### ISSUE TITLE
New Search Icon at the right corner.

### ISSUE THREAD

**Issue by GouthamKD** [Osedea/react-native-action-bar#11]
Hello All,

Can you please let me know on **how to include new icons(search)  beside the phone and star icon in the right side** 

I have tried below snippet ,but I dont see the icon getting pulled from the path provided

++++++++++++++++++++++
// sample code below.

    {
              name: 'search',
              badge:1,
              rightIconImage:require('./images/search.png'),
              isBadgeLeft:true,
              onPress: () => Alert.alert('search pressed!')
            },

+++++++++++++++

please let me know your thoughts.

Thanks,
Goutham KD

**Comment by adrienthiery** [comment]
Hi @GouthamKD,

The way you pass a custom image is the basic react-native way, so it should work right away...

What is the result right now? Do you have an error or the icon just doesn't show?

Could I get a more extensive snippet of the code you use to use react-native-action-bar? 

Thanks in advance :)

**Comment by GouthamKD** [comment]
Hi adrienthiery,

thanks for the response.

Please find below snippet I used to render the Search icon on the Action bar..

++++++++++++++++++++++++++++++++++++++

import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Alert,
} from 'react-native';
import ActionBar from 'react-native-action-bar';
export default class Example extends Component {

starClick=()=>{
Alert.alert('Star is clicked!!');  

}

 render() {
    return (
      <View style={styles.container}>
        <ActionBar
          containerStyle={styles.bar}
          title={'React-native-action-bar Example'}
          rightText={'Hello KD'}
          leftIconName={'menu'}
          backgroundColor={'blue'}
          leftBadge={''}
          onLeftPress={() => console.log('Left!')}
          onTitlePress={() => console.log('Title!')}
          rightIcons={[

            // Code for importing the the Search Icon below..

            {
              name: 'search',
              badge:'1',
              source : require('./images/search.png'),
              onPress:()=> Alert.alert('search is pressed!!')
            },

            
            {
              name: 'flag',
              badge: '1',
              onPress: () => console.log('Right Flag !'),
            },
          ]}
        />
        <Text style={styles.welcome}>
          Welcome to React Native!
                </Text>
      </View>
    );
  }
}

+++++++++++++++++++++++++++++++++++++

Let me know what more changes required to have the Search Icon rendered on the action bar.


Thanks in Advance,
Goutham KD

**Comment by subsub** [comment]
@GouthamKD Turns out, after seeing the code, the parameter used is not `source`, but `image`.
So try to change:
```
source : require('./images/search.png'),
```
into
```
image : require('./images/search.png'),
```

**Comment by adrienthiery** [comment]
Hi guys, sorry for the delay.

You're right @subsub , it seems to be `image` in a rightIcons element. I'll update the docs right away

**Comment by adrienthiery** [comment]
Updated in b0f99d3313c55a7dbc6245ebadf9aac597267b6a
