### ISSUE TITLE
Android app crash on release. caused by View.propTypes.style

### ISSUE THREAD

**Issue by sarykemmoun** [Osedea/react-native-action-bar#12]
Hello.
Since RN.44 View.PropTypes changed to ViewPropTypes.
Release crash since your library still uses View.propTypes.
`AndroidRuntime: com.facebook.react.common.JavascriptException: undefined is not an object (evaluating 'i.View.propTypes.style')`
Do you have a version with a fix for this issue?
Thanks.

**Comment by adrienthiery** [comment]
Hi @sarykemmoun ,

Just published 2.0.4 to fix that and 2.0.5 to remove the annoying warning caused by the `rightIcons` propTypes 🙂

Thanks for pointing it out!
