### ISSUE TITLE
Not showing icon with expo in emulator

### ISSUE THREAD

**Issue by pashute** [Osedea/react-native-action-bar#14]
What am I doing wrong?

The left icon is not being shown in the action bar, 
but is shown ok if I load it on the page in a separate image element (and not in action-bar). 

I have: 

    import React, { Component } from 'react';
    import { Platform, StyleSheet, Text, View /*, Alert*/ } from 'react-native';
    const earIcon = require('../assets/icons/ear1.png');

I also tried loading it in the render function: 
    
    let earIcon = require('../assets/icons/ear1.png');

In the render function I have: 

    <ActionBar
                    containerStyle={styles.actionBar}
                    titleStyle={styles.actionTitle}
                    title={'noam'}
                    leftIconImage={earIcon}
                    onLeftPress={() => console.log('Talk Icon pressed.')}
                    rightIcons={[
                      {
                        name: 'menu',
                        onPress: this.toggleDrawer
                      }
                    ]}
    />

The styles are 

    actionBar: {
    /* ear appname and menu */
    backgroundColor: '#330077'
  },
  actionTitle: {
    textAlign: 'center',
    fontSize: 20
  },

I'm developing on VSCode in Windows 10. Running with expo. My versions: 

    Environment:
    OS: Windows 10
    Node: 8.11.1
    Yarn: 1.7.0
    npm: 6.1.0
    Watchman: Not Found
    Xcode: N/A
    Android Studio: Version  3.1.0.0 AI-173.4670197

  Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.3 => 0.55.3

Running with expo version 27.0
on Genimotion emulator.

**Comment by adrienthiery** [comment]
Your usage seems correct to me...

Could you share a [snack](https://snack.expo.io/) reproducing the issue, by any chance ? 

What are the dimensions of your `ear` image ?

Thanks in advance

**Comment by adrienthiery** [comment]
Seems to work on Snack as well : https://snack.expo.io/rk_yQ-7lQ

Not the same image, but otherwise I took all of your code.

**Comment by adrienthiery** [comment]
If you manage to reproduce on Snack, or if you can share the image you are using, please feel free to re-open 🙂

**Comment by pashute** [comment]
Thanks. I'll check dimensions and get back tomorrow.
