### ISSUE TITLE
Exclude example folder from npm module.

### ISSUE THREAD

**Issue by jerinjohnk** [Osedea/react-native-action-bar#16]
Currently for version 2.0.2 on including this npm pakage, Example folder is also added.
Now this folder is almost 185MB in size.
Is it really necessary to include this folder for creating a build, or can we delete it?

**Comment by adrienthiery** [comment]
Indeed, it is not, I'll remove it as soon as I can, sorry about that!

**Comment by adrienthiery** [comment]
Hi @jerinjohnk ,
Finally got back to work (🤔😅😇), and looking into this.
Is there a reason you would use version 2.0.2 instead of 2.0.5 ? 🤔 

Because 2.0.5 does not include the example package, so you should use this version instead.

**Comment by jerinjohnk** [comment]
My bad. Looks like my colleague had fixed the version coz of some node_module changes we made for this. Will update it to latest one.
