### ISSUE TITLE
Title text is not centered

### ISSUE THREAD

**Issue by Venryx** [Osedea/react-native-action-bar#3]
At least it wasn't when placed in my app's existing ui.

**Comment by adrienthiery** [comment]
Hi @Venryx ,

Sorry for the delay.

Could you give me a bit more detail on the version of react-native you used and the code around where you used the component, please ?

**Comment by adrienthiery** [comment]
Hi @Venryx ,

I'm closing that issue, as the component has changed a lot in the past few weeks.

Feel free to reopen if you still have issues with this.
